<?xml version="1.0"?>
<package format="3">
  <name>arctos_description</name>
  <version>0.1.0</version>
  <description>Initial Arctos description using locally purchased CAD meshes.</description>
  <maintainer email="gsylvia@example.com">gsylvia</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <!-- Offline mesh and joint limit scripts. -->
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-vtk9</exec_depend>
  <!-- display.launch.py -->
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
