cmake_minimum_required(VERSION 3.8)
project(arctos_collision_demo)
find_package(ament_cmake REQUIRED)
set(dependencies rclcpp moveit_core sensor_msgs geometry_msgs visualization_msgs geometric_shapes urdf srdfdom)
foreach(dependency IN LISTS dependencies)
  find_package(${dependency} REQUIRED)
endforeach()
add_executable(collision_demo src/collision_demo.cpp)
target_compile_features(collision_demo PUBLIC cxx_std_17)
ament_target_dependencies(collision_demo ${dependencies})
install(TARGETS collision_demo DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
ament_package()
